### ISSUE TITLE
translate command only translates the first sentence

### ISSUE THREAD

**Issue by crycode-de** [ioBroker/adapter-dev#127]
When running `npm run translate` to tanslate the i18n json files, only the first sentence of each string gets translated.
Any further sentence is dropped from the translation.

Especially for the `help` texts in jsonConfig, sometimes multiple sentences in one string are required.

Example:
**en** (source)
```json
"Emoji to react with on mentions. Default is 👍.": "Emoji to react with on mentions. Default is 👍.",
```

**de** (tranlated)
```json
"Emoji to react with on mentions. Default is 👍.": "Emoji zum Reagieren auf Erwähnungen. ",
```
(note the space at the end)

**Comment by SKB-CGN** [comment]
A very important function is open since Apil ...

**Comment by Apollon77** [comment]
@SKB-CGN You are invited to send in a PR

**Comment by Apollon77** [comment]
Ok, I found the reason ... basically it is https://github.com/ioBroker/adapter-dev/blob/main/src/translate.ts#L142

When you have two sentences then the response is splitted:

```json
[[["Das ist ein Test. ","This is a Test.",null,null,1],["Huhu","huhu",null,null,3,null,null,[[]],[[["7b93c30c104c18c11fe0f772962f0fd2","en_de_2022q1.md"]]]]],null,"en",null,null,null,null,[]]
```
