### ISSUE TITLE
Long translations are not accepted

### ISSUE THREAD

**Issue by SKB-CGN** [ioBroker/adapter-dev#161]
Hi,
if you have a translation like this in the json file
`"ex_custom_circle_icon":"How to get the Icon? Visit <a href='_top'>https://materialdesignicons.com</a> and search for an icon. Click the Icon and in the below row click '</>', choose 'View SVG' and copy only the text inside <b>d</b>",
`
It will be cut after: How to get the Icon?

**Comment by crycode-de** [comment]
Same like #127
