### ISSUE TITLE
build witch watch option is going to wrong directory or wrong directory is linked

### ISSUE THREAD

**Issue by oweitman** [ioBroker/adapter-dev#201]
in the options the .watch directory is defined if you start the admin ui developement for an adapter in react.
but in the template of the html page there is fixed the build directory linked.
https://github.com/ioBroker/create-adapter/blob/61859f109562d2a9072c1288381455a879d28510/templates/admin/index_m.html.ts#L110
this should be dynamic

https://github.com/ioBroker/adapter-dev/blob/b9e00e3d2de91a7d928b46022a29ba8c5e00505c/src/build-adapter.ts#L25

**Comment by mcm1957** [comment]
@AlCalzone 
@UncleSamSwiss 
@Apollon77 

any comments?

**Comment by AlCalzone** [comment]
From the issue description, I have no idea what to do to reproduce this without spending an hour to try and figure out what you did. Please share the steps you used to get to this point. A commit of your adapter or the `.create-adapter.json` file should do.

**Comment by oweitman** [comment]
may be this question should be asked in december and not months after.
in meantime i forgot that was the matter of this issue
to try again (in general the adapter developement) my motivation is missing, because i know, next time i ask something,
there is also no response
and there is no working workflow to establish a developement environment there i can read
for some special cases it is ok to ask in forum, discord, telegram
but since beginning of my experiments, the start was difficult always
