### ISSUE TITLE
Provide a shared ESLint config

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/adapter-dev#5]
Separate for JS/TS

https://eslint.org/docs/developer-guide/shareable-configs

**Comment by UncleSamSwiss** [comment]
When implementing, please have a look at ioBroker/create-adapter#569, so we don't forget anything.

**Comment by hombach** [comment]
Looks like this isn't necessary anymore as there is "@iobroker/eslint-config"

**Comment by Apollon77** [comment]
right
